version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    volumes:
    - ./postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: root
  graphql-engine:
    image: hasura/graphql-engine:latest
    ports:
    - "80:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:root@postgres:5432/postgres
      PG_DATABASE_URL: postgres://postgres:root@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" 
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
volumes:
  db_data: